sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: WBeH4p5AAvnZkTcVXsHR0ahmL2CjhHHV+nw7RzIvJ6nvZk0/QXCcxZaJChnIf3Yxhzi+UYMtuBM2l+7OrjAXZ6ypyHJcFXbCsvtycrcKjOUhBb2cTMFuh41fe6b+48462pN1kMU9pjt1ot0XxlRlHVoPrxnKgV7J1M2CKSAl/ek=
  on:
    tags: true
    all_branches: true
